/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SearchQuery } from "./SearchQuery";
import { SearchQueryCountArgs } from "./SearchQueryCountArgs";
import { SearchQueryFindManyArgs } from "./SearchQueryFindManyArgs";
import { SearchQueryFindUniqueArgs } from "./SearchQueryFindUniqueArgs";
import { DeleteSearchQueryArgs } from "./DeleteSearchQueryArgs";
import { SearchQueryService } from "../searchQuery.service";
@graphql.Resolver(() => SearchQuery)
export class SearchQueryResolverBase {
  constructor(protected readonly service: SearchQueryService) {}

  async _searchQueriesMeta(
    @graphql.Args() args: SearchQueryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SearchQuery])
  async searchQueries(
    @graphql.Args() args: SearchQueryFindManyArgs
  ): Promise<SearchQuery[]> {
    return this.service.searchQueries(args);
  }

  @graphql.Query(() => SearchQuery, { nullable: true })
  async searchQuery(
    @graphql.Args() args: SearchQueryFindUniqueArgs
  ): Promise<SearchQuery | null> {
    const result = await this.service.searchQuery(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SearchQuery)
  async deleteSearchQuery(
    @graphql.Args() args: DeleteSearchQueryArgs
  ): Promise<SearchQuery | null> {
    try {
      return await this.service.deleteSearchQuery(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
