/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SearchAnalytics as PrismaSearchAnalytics,
} from "@prisma/client";

export class SearchAnalyticsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SearchAnalyticsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.searchAnalytics.count(args);
  }

  async searchAnalyticsItems<T extends Prisma.SearchAnalyticsFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SearchAnalyticsFindManyArgs>
  ): Promise<PrismaSearchAnalytics[]> {
    return this.prisma.searchAnalytics.findMany<Prisma.SearchAnalyticsFindManyArgs>(
      args
    );
  }
  async searchAnalytics<T extends Prisma.SearchAnalyticsFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SearchAnalyticsFindUniqueArgs>
  ): Promise<PrismaSearchAnalytics | null> {
    return this.prisma.searchAnalytics.findUnique(args);
  }
  async createSearchAnalytics<T extends Prisma.SearchAnalyticsCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SearchAnalyticsCreateArgs>
  ): Promise<PrismaSearchAnalytics> {
    return this.prisma.searchAnalytics.create<T>(args);
  }
  async updateSearchAnalytics<T extends Prisma.SearchAnalyticsUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SearchAnalyticsUpdateArgs>
  ): Promise<PrismaSearchAnalytics> {
    return this.prisma.searchAnalytics.update<T>(args);
  }
  async deleteSearchAnalytics<T extends Prisma.SearchAnalyticsDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SearchAnalyticsDeleteArgs>
  ): Promise<PrismaSearchAnalytics> {
    return this.prisma.searchAnalytics.delete(args);
  }
}
